### ISSUE TITLE
Better calendar card styles

### ISSUE THREAD

**Issue by derekeder** [chihacknight/chihacknight.org#26]
These look nice: http://east13.gomodev.com/#schedule

``` css

.date-picker { float: left; padding-bottom: 30px; width: 100%; }
.date-picker a { background: #f1f1f1; border-radius: 6px; color: #898989; display: inline-block; height: 112px; width: 104px; }
.date-picker a.central { margin: 0 33px; }
.date-picker .weekday { border-bottom: 2px solid #fff; display: block; font: bold 14px Montserrat; padding: 8px 0 6px; text-transform: uppercase; }
.date-picker .date { display: block; font-size: 42px; padding: 15px 0 5px; }
.date-picker .month { font-size: 14px; text-transform: uppercase; }

.date-picker .active { background: #fff; border: 2px solid #202020; color: #121212; }
.date-picker .active .weekday { border-color: #202020; }

```
